import { isOrchardFruitTree, normalizeGardenLocation } from "../utils/plantClassification.js";
import { selectBuddyEstateUpdates } from "../utils/buddyUpdates.js";

export const companions={buddy:{name:"Buddy",title:"Estate Companion",tone:"Concise estate updates",prompts:["What needs attention today?","What should I water?","What changed in the garden recently?","Give me today’s estate update."]},gardener:{name:"The Head Gardener",title:"Horticulture Advisor",tone:"Practical care and planning",prompts:["Which plants need care?","When was Ms. Quatt last watered?","Summarize my orchard.","Which garden zone needs the most attention?"]},herbalist:{name:"The Herbalist",title:"Tea and Herb Advisor",tone:"Herbs, tea, drying, and blending",prompts:["Which tea blends can I make?","List all 25 mint varieties.","Which herbs are ready to harvest?","Summarize my From Garden to Cup workflows."]}};
const clean=(value="")=>String(value).toLocaleLowerCase().replace(/[’']/g,"").replace(/\s+/g," ").trim();
const source=(type,label,id)=>({type,label,id});
const result=(text,sources=[],actions=[])=>({text,sources,actions,mode:"Jardin Soleil records · local rules",timestamp:new Date().toISOString()});
const plantIdentity=(plant)=>clean([plant.name,plant.nickname,plant.variety,plant.botanicalName].filter(Boolean).join(" "));
const findPlant=(question,plants,scope)=>scope||plants.find((plant)=>{const terms=[plant.name,plant.nickname].filter(Boolean).map(clean);return terms.some((term)=>term&&clean(question).includes(term));});
const careEntries=(journal)=>journal.filter((entry)=>entry.careEvent);
const overdue=(journal)=>{const today=new Date();today.setHours(0,0,0,0);return careEntries(journal).filter((entry)=>entry.nextDueDate&&new Date(`${entry.nextDueDate}T12:00:00`)<today);};
const weatherLabel=(environment)=>environment.status==="ready"?"Live":environment.status==="cached"?"Cached":environment.status==="disabled"?"Manual":"Unavailable";

export function answerLocally({question,companion,data,scopePlant=null}) {
  const q=clean(question); const plants=data.plants||[]; const journal=data.journalEntries||[]; const blends=data.teaBlends||[]; const workflows=data.teaWorkflows||[]; const env=data.environment||{};
  const scoped=findPlant(q,plants,scopePlant); const needing=plants.filter((plant)=>plant.health!==undefined&&Number(plant.health)<85); const late=overdue(journal);
  if(/prune/.test(q)){
    const end=new Date(); end.setDate(end.getDate()+7);
    const due=careEntries(journal).filter((entry)=>entry.nextDueDate&&clean(entry.type).includes("prun")&&new Date(`${entry.nextDueDate}T12:00:00`)<=end);
    return result(due.length?`Saved Jardin Soleil facts: ${due.map((entry)=>`${plants.find((plant)=>plant.id===entry.plantId)?.name||"Unknown plant"} has pruning due ${entry.nextDueDate}`).join("; ")}.`:"No pruning care entry is saved as due within the next seven days. This does not mean pruning is horticulturally unnecessary; it means no due record exists.",due.map((entry)=>source("care",entry.type||"Pruning",entry.id)));
  }
  if(/blend with|flavor|caffeine|wellness/.test(q)){
    const term=q.replace(/^.*(?:with|flavor|caffeine|wellness)\s+/,"");
    const matches=blends.filter((blend)=>[...(blend.ingredients||[]),...(blend.flavorProfile||[]),...(blend.wellnessBenefits||[]),blend.caffeineLevel].some((value)=>q.includes(clean(value))||clean(value).includes(term)));
    return result(matches.length?`Saved Tea Apothecary matches: ${matches.map((blend)=>`${blend.name} (${blend.ingredients.join(", ")})`).join("; ")}.`:"No saved tea blend matches that ingredient, flavor, caffeine, or wellness term. I have not claimed an unsaved blend exists.",matches.map((blend)=>source("blend",blend.name,blend.id)),[{label:"Open Tea Apothecary",page:"Tea Apothecary"}]);
  }
  if(/running low|pantry|inventory report/.test(q)){
    const low=blends.filter((blend)=>Number(blend.inventory?.quantity||0)<=5);
    return result(low.length?`No separate per-ingredient pantry quantities are saved. Saved blend inventory at or below the five-serving local review threshold: ${low.map((blend)=>`${blend.name}: ${blend.inventory.quantity} ${blend.inventory.unit}`).join("; ")}.`:"No separate per-ingredient pantry quantities are saved, and no saved blend inventory is at or below the five-serving local review threshold.",low.map((blend)=>source("blend",blend.name,blend.id)));
  }
  if(/weekly garden report|monthly garden summary|seasonal care review/.test(q)){
    const days=q.includes("weekly")?7:q.includes("monthly")?30:90;
    const cutoff=Date.now()-(days*86400000);
    const recent=journal.filter((entry)=>new Date(entry.createdAt||entry.date||0).getTime()>=cutoff);
    const period=q.includes("weekly")?"weekly":q.includes("monthly")?"monthly":"seasonal";
    const healthKnown=plants.filter((plant)=>plant.health!==undefined&&plant.health!==null&&plant.health!=="");
    return result(`Saved Jardin Soleil ${period} report: ${plants.length} active plants, ${recent.length} journal or care entries in the last ${days} days, ${late.length} overdue care entries, and ${needing.length} plants below 85% recorded health. ${healthKnown.length===plants.length?"Health values are recorded for every active plant.":`Health data is not recorded for ${plants.length-healthKnown.length} active plants.`}`,recent.map((entry)=>source("journal",entry.title||entry.type||"Garden entry",entry.id)),[{label:"Open Journal",page:"Logbook"},{label:"Open Plant Directory",page:"Plant Directory"}]);
  }
  if(scoped&&/care.*overdue|overdue.*care/.test(q)){
    const entries=late.filter((entry)=>entry.plantId===scoped.id);
    return result(entries.length?`Saved Jardin Soleil facts: ${scoped.name} has ${entries.length} overdue care ${entries.length===1?"entry":"entries"}: ${entries.map((entry)=>`${entry.type||"Care"} due ${entry.nextDueDate}`).join("; ")}.`:`No care entry for ${scoped.name} is saved as overdue.`,[source("plant",scoped.name,scoped.id),...entries.map((entry)=>source("care",entry.type||"Care entry",entry.id))],[{label:"Open Plant Profile",page:"Plant Profile",plantId:scoped.id}]);
  }
  if(scoped&&/summarize.*history|plant.*history/.test(q)){
    const entries=journal.filter((entry)=>entry.plantId===scoped.id).sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));
    return result(entries.length?`Saved Jardin Soleil facts: ${scoped.name} has ${entries.length} linked history ${entries.length===1?"entry":"entries"}. Most recent: ${entries.slice(0,3).map((entry)=>`${entry.type||entry.title||"Garden note"} on ${new Date(entry.createdAt||entry.date).toLocaleDateString()}`).join("; ")}.`:`No journal or care history is linked to ${scoped.name}.`,[source("plant",scoped.name,scoped.id),...entries.map((entry)=>source("journal",entry.title||entry.type||"Garden entry",entry.id))],[{label:"Open Plant Profile",page:"Plant Profile",plantId:scoped.id}]);
  }
  if(scoped&&/watch.*season|season.*watch/.test(q)){
    return result(`Saved Jardin Soleil facts for ${scoped.name}: status ${scoped.status||"not recorded"}, health ${scoped.health??"not recorded"}${scoped.health!==undefined?"%":""}, sun ${scoped.sun||"not recorded"}, and water needs ${scoped.water||"not recorded"}. General seasonal guidance: observe new growth, soil moisture, pests, and weather stress; this is not a diagnosis.`,[source("plant",scoped.name,scoped.id)],[{label:"Open Plant Profile",page:"Plant Profile",plantId:scoped.id}]);
  }
  if(/how many.*fruit|fruit tree count/.test(q)){const orchard=plants.filter(isOrchardFruitTree);return result(`Saved Jardin Soleil fact: ${orchard.length} active fruit trees are recorded.`,orchard.map((p)=>source("plant",p.name,p.id)),[{label:"Open Orchard",page:"Orchard"}]);}
  if(/list.*mint|mint variet/.test(q)){const mints=plants.filter((p)=>p.type==="Mint"&&p.id!=="mint-collection").sort((a,b)=>a.name.localeCompare(b.name));return result(mints.length?`Saved Jardin Soleil fact: ${mints.length} mint varieties are recorded — ${mints.map((p)=>p.name).join(", ")}.`:"No individual mint records were found.",mints.map((p)=>source("plant",p.name,p.id)),[{label:"Open Plant Directory",page:"Plant Directory"}]);}
  if(/last water|when.*water/.test(q)){if(!scoped)return result("I couldn’t identify a saved plant for that watering question. Please use its saved name or nickname.");const entry=[...journal].filter((e)=>e.plantId===scoped.id&&clean(e.type).includes("water")).sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0))[0];return result(entry?`Saved Jardin Soleil fact: ${scoped.name} was last watered on ${new Date(entry.createdAt).toLocaleDateString()}.`:`I don’t have a watering record for ${scoped.name} yet.`,[source("plant",scoped.name,scoped.id),...(entry?[source("care","Watering record",entry.id)]:[])],[{label:"Open Plant Profile",page:"Plant Profile",plantId:scoped.id}]);}
  if(/need.*care|needs attention|attention today/.test(q)){const ids=new Set(late.map((e)=>e.plantId));const affected=[...needing,...plants.filter((p)=>ids.has(p.id))].filter((p,i,a)=>a.findIndex(x=>x.id===p.id)===i);return result(affected.length?`Saved Jardin Soleil facts: ${affected.length} active ${affected.length===1?"plant needs":"plants need"} attention — ${affected.map((p)=>p.name).join(", ")}.`:"No saved health or overdue-care record currently identifies a plant needing attention.",affected.map((p)=>source("plant",p.name,p.id)),[{label:"Open Plant Directory",page:"Plant Directory"}]);}
  if(/what should i water|water today/.test(q)){const due=careEntries(journal).filter((e)=>e.nextDueDate===new Date().toISOString().slice(0,10)&&clean(e.type).includes("water"));return result(due.length?`Saved Jardin Soleil facts: ${due.length} watering ${due.length===1?"task is":"tasks are"} due today — ${due.map((e)=>plants.find((p)=>p.id===e.plantId)?.name||"Unknown plant").join(", ")}.`:"No watering task is saved as due today. Check soil moisture before deciding to water.",due.map((e)=>source("care",plants.find((p)=>p.id===e.plantId)?.name||"Watering task",e.id)));}
  if(/summarize.*orchard|orchard summary|orchard health report/.test(q)){const orchard=plants.filter(isOrchardFruitTree);const known=orchard.filter((p)=>p.health!==undefined);const low=known.filter((p)=>p.health<85);return result(`Saved Jardin Soleil facts: ${orchard.length} active orchard trees are recorded. ${known.length?`${known.length} have saved health values; ${low.length} are below 85%.`:"No orchard health values are saved."}`,orchard.map((p)=>source("plant",p.name,p.id)),[{label:"Open Orchard",page:"Orchard"}]);}
  if(/zone.*attention|garden zone/.test(q)){const known=plants.filter((p)=>p.health!==undefined&&normalizeGardenLocation(p.location));if(!known.length)return result("I don’t have enough saved plant-health and location data to identify a garden zone needing the most attention.");const grouped={};known.forEach((p)=>{const z=normalizeGardenLocation(p.location);(grouped[z]??=[]).push(p);});const ranked=Object.entries(grouped).map(([zone,items])=>({zone,average:Math.round(items.reduce((s,p)=>s+Number(p.health),0)/items.length),items})).sort((a,b)=>a.average-b.average);const first=ranked[0];return result(`Saved Jardin Soleil facts: ${first.zone} has the lowest recorded average health at ${first.average}% across ${first.items.length} ${first.items.length===1?"plant":"plants"}.`,first.items.map((p)=>source("plant",p.name,p.id)));}
  if(/ready to harvest|harvest ready|what is ready|harvest report/.test(q)){const ready=plants.filter((p)=>/producing|fruiting|harvest ready|ready to harvest/i.test(p.status||""));return result(ready.length?`Saved Jardin Soleil facts: ${ready.map((p)=>`${p.name} (${p.status})`).join(", ")}.`:"No plant is currently marked harvest-ready in saved records.",ready.map((p)=>source("plant",p.name,p.id)),[{label:"View Harvest History",page:"Logbook"}]);}
  if(/tea apothecary|tea blends|blends can i make|what can i make/.test(q)){const available=blends.filter((b)=>Number(b.inventory?.quantity||0)>0);return result(available.length?`Saved Tea Apothecary facts: ${available.length} blends have recorded inventory — ${available.map((b)=>`${b.name} (${b.inventory.quantity} ${b.inventory.unit})`).join(", ")}.`:"No saved tea blend currently has recorded inventory.",available.map((b)=>source("blend",b.name,b.id)),[{label:"Open Tea Apothecary",page:"Tea Apothecary"}]);}
  if(/running low|pantry|inventory report/.test(q)){const low=blends.filter((b)=>Number(b.inventory?.quantity||0)<=5);return result(low.length?`Saved inventory facts: ${low.map((b)=>`${b.name}: ${b.inventory.quantity} ${b.inventory.unit}`).join("; ")}. “Low” here uses the local review rule of five servings or fewer.`:"No saved blend inventory is at or below the five-serving local review threshold.",low.map((b)=>source("blend",b.name,b.id)));}
  if(/garden to cup|workflow/.test(q)){return result(workflows.length?`Saved Garden-to-Cup facts: ${workflows.length} workflows are recorded — ${workflows.map((w)=>`${plants.find((p)=>p.id===w.plantId)?.name||"Unknown herb"}: ${w.currentStage}`).join("; ")}.`:"No Garden-to-Cup workflows are saved.",workflows.map((w)=>source("workflow",w.currentStage,w.id)),[{label:"Open Tea Apothecary",page:"Tea Apothecary"}]);}
  if(/brew|steep|temperature/.test(q)){const blend=blends.find((b)=>q.includes(clean(b.name)));return result(blend?`Saved recipe: ${blend.name} uses ${blend.brewing.temperature}, steeps for ${blend.brewing.steepTime}, and measures ${blend.brewing.serving}.`:"I couldn’t match that question to a saved Tea Apothecary blend.",blend?[source("blend",blend.name,blend.id)]:[]);}
  if(/weather|rain|heat|wind|snow|frost/.test(q)){const status=weatherLabel(env);return result(status==="Unavailable"?"The current weather source is unavailable.":`${status} estate weather: ${env.conditionLabel||env.condition||"condition unavailable"}${env.weather?.temperature!==undefined?`, ${env.weather.temperature}°F`:""}. Suggestions are based on this recorded weather status.`,env.weather?[source("weather",`${status} weather`,env.weather.observedAt)]:[]);}
  if(/recent|changed|estate update|daily estate/.test(q)){const estate=selectBuddyEstateUpdates({plants,journalEntries:journal,photos:data.photos||[]});return result(estate.updates.length?estate.updates.slice(0,companion==="buddy"?2:5).map((x)=>x.text).join(" "):"No meaningful update is available from the current saved records.",estate.updates.map((x)=>source("local rule",x.text,x.id)),[{label:"Open Journal",page:"Logbook"}]);}
  if(scoped){return result(`Saved Jardin Soleil facts for ${scoped.name}: category ${scoped.category||"not recorded"}, type ${scoped.type||"not recorded"}, status ${scoped.status||"not recorded"}, location ${scoped.location||"not recorded"}. I can give general guidance, but I don’t have enough saved information to diagnose symptoms that were not recorded.`,[source("plant",scoped.name,scoped.id)],[{label:"Open Plant Profile",page:"Plant Profile",plantId:scoped.id}]);}
  return result("I couldn’t find a saved Jardin Soleil record that answers that question. Try asking for a plant by name, an orchard summary, due care, mint varieties, tea inventory, Garden-to-Cup workflows, or weather status.");
}

export async function answerWithOptionalExternal({question,companion,data,scopePlant,settings}) {
  const local=answerLocally({question,companion,data,scopePlant}); if(!settings.externalAI)return local;
  const payload={question,companion,scopePlant:scopePlant?{id:scopePlant.id,name:scopePlant.name}:null,relevantSources:local.sources.map(({type,label,id})=>({type,label,id})),localAnswer:local.text};
  try{const response=await fetch("/.netlify/functions/conservatory",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("External provider unavailable");const external=await response.json();return{...local,text:external.answer||local.text,mode:"External AI · minimized Jardin Soleil context"};}catch{return{...local,mode:`${local.mode} · external unavailable`};}
}
