import React, { useState } from "react";
import { useGarden } from "../context/GardenContext";
import { plantCategories, plantGroups, suggestPlantGroup, validateAndNormalizePlant } from "../utils/plantMutations";
import "./PlantEditor.css";

const editableFields=["name","nickname","type","category","group","variety","botanicalName","gardenZone","location","status","health","sun","water","plantingDate","acquisitionDate","source","notes","iconType","tags"];
const blank={name:"",nickname:"",type:"",category:"",group:"",variety:"",botanicalName:"",gardenZone:"",location:"",status:"",health:"",sun:"",water:"",plantingDate:"",acquisitionDate:"",source:"",notes:"",iconType:"",tags:""};
const initialFor=(plant)=>plant?{...blank,...plant,health:plant.health??"",tags:(plant.tags||[]).join(", ")}:blank;

export default function PlantEditor({plant,onCancel,onSaved,onOpenExisting}) {
  const {plants,addPlant,updatePlant,addPhotos}=useGarden();
  const [form,setForm]=useState(()=>initialFor(plant)); const [errors,setErrors]=useState({}); const [duplicates,setDuplicates]=useState([]); const [allowDuplicate,setAllowDuplicate]=useState(false); const [photo,setPhoto]=useState(null);
  const change=(field,value)=>{setForm((current)=>{const next={...current,[field]:value};if((field==="type"||field==="category")&&!current.group)next.group=suggestPlantGroup(next);return next;});setErrors((current)=>({...current,[field]:undefined}));setAllowDuplicate(false);};
  const save=async(event)=>{event.preventDefault();const result=validateAndNormalizePlant(form,plants,plant?.id||null);setErrors(result.errors);setDuplicates(result.duplicates);if(!result.valid||(result.duplicates.length&&!allowDuplicate))return;let saved=result.record;
    if(plant){updatePlant(plant.id,(current)=>{const next={...current};editableFields.forEach((field)=>delete next[field]);return{...next,...result.record,id:plant.id,createdAt:plant.createdAt||result.record.createdAt};});saved={...plant,...result.record,id:plant.id};}else addPlant(saved);
    if(photo){const url=await new Promise((resolve)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(photo);});addPhotos([{id:`plant-photo-${Date.now()}`,plantId:saved.id,name:photo.name,date:new Date().toISOString(),url}]);}
    onSaved(saved);
  };
  return <section className="js-plant-editor" aria-labelledby="plant-editor-title"><header><p>Jardin Soleil · Garden Registry</p><h1 id="plant-editor-title">{plant?"Edit Plant":"Add New Plant"}</h1><span>{plant?"Refine this estate record without disturbing its history.":"Register a plant in the canonical Jardin Soleil collection."}</span></header>
    <form onSubmit={save} noValidate>
      <fieldset><legend>Identity</legend><Field label="Display name" required error={errors.name}><input value={form.name} onChange={(e)=>change("name",e.target.value)}/></Field><Field label="Nickname"><input value={form.nickname} onChange={(e)=>change("nickname",e.target.value)}/></Field><Field label="Plant type" required error={errors.type}><input value={form.type} onChange={(e)=>change("type",e.target.value)} placeholder="e.g. Plum, Mint, Tomato, Rose"/></Field><Field label="Category" required error={errors.category}><select value={form.category} onChange={(e)=>change("category",e.target.value)}><option value="">Select category</option>{plantCategories.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="Group"><select value={form.group} onChange={(e)=>change("group",e.target.value)}><option value="">Use suggested group</option>{plantGroups.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="Variety or cultivar"><input value={form.variety} onChange={(e)=>change("variety",e.target.value)}/></Field><Field label="Botanical name"><input value={form.botanicalName} onChange={(e)=>change("botanicalName",e.target.value)}/></Field><Field label="Icon type"><input value={form.iconType} onChange={(e)=>change("iconType",e.target.value)} placeholder="e.g. mint, peach, rose"/></Field></fieldset>
      <fieldset><legend>Estate placement & care</legend><Field label="Garden zone"><input value={form.gardenZone} onChange={(e)=>change("gardenZone",e.target.value)}/></Field><Field label="Specific location"><input value={form.location} onChange={(e)=>change("location",e.target.value)}/></Field><Field label="Status"><input value={form.status} onChange={(e)=>change("status",e.target.value)}/></Field><Field label="Health percentage" error={errors.health}><input type="number" min="0" max="100" value={form.health} onChange={(e)=>change("health",e.target.value)}/></Field><Field label="Sun requirements"><input value={form.sun} onChange={(e)=>change("sun",e.target.value)}/></Field><Field label="Water needs"><input value={form.water} onChange={(e)=>change("water",e.target.value)}/></Field><Field label="Planting date" error={errors.plantingDate}><input type="date" value={form.plantingDate} onChange={(e)=>change("plantingDate",e.target.value)}/></Field><Field label="Acquisition date" error={errors.acquisitionDate}><input type="date" value={form.acquisitionDate} onChange={(e)=>change("acquisitionDate",e.target.value)}/></Field><Field label="Source or nursery"><input value={form.source} onChange={(e)=>change("source",e.target.value)}/></Field><Field label="Tags"><input value={form.tags} onChange={(e)=>change("tags",e.target.value)} placeholder="comma separated"/></Field><Field label="Photo"><input type="file" accept="image/*" onChange={(e)=>setPhoto(e.target.files?.[0]||null)}/></Field><Field label="Notes" wide><textarea rows="4" value={form.notes} onChange={(e)=>change("notes",e.target.value)}/></Field></fieldset>
      {duplicates.length>0&&!allowDuplicate&&<aside className="js-plant-editor__duplicates" role="alert"><h2>Possible duplicate</h2><p>A saved plant shares this name, nickname, variety, or botanical name.</p>{duplicates.map((item)=><button type="button" key={item.id} onClick={()=>onOpenExisting(item)}>Open {item.name}</button>)}<button type="button" onClick={()=>setAllowDuplicate(true)}>Save anyway</button></aside>}
      <div className="js-plant-editor__actions"><button type="button" onClick={onCancel}>Cancel</button><button type="submit">{plant?"Save Plant Changes":"Add Plant"}</button></div>
    </form></section>;
}
function Field({label,required,error,wide,children}){return <label className={wide?"is-wide":""}><span>{label}{required?" *":""}</span>{children}{error&&<small role="alert">{error}</small>}</label>}
