const disease = (id, name, data) => ({ id, name, category:"Disease", ...data });
const pest = (id, name, data) => ({ id, name, category:"Pest", ...data });
const stress = (id, name, data) => ({ id, name, category:"Environmental stress", ...data });

export const plantHealthRules = [
  disease("powdery-mildew", "Powdery mildew", { areas:["leaves", "stems", "flowers"], symptoms:["white powder", "curling", "distorted growth", "yellowing"], conditions:["cloudy", "high humidity"], inspect:"Look for wipeable white growth on both leaf surfaces and nearby plants.", cultural:"Increase spacing and airflow, keep foliage dry, and remove heavily affected material." }),
  disease("black-spot", "Black spot", { areas:["leaves", "stems"], symptoms:["black spots", "yellowing", "leaf drop"], plantTerms:["rose"], conditions:["heavy rain", "high humidity"], inspect:"Check lower leaves for round dark lesions with fringed margins and progressive yellowing.", cultural:"Remove fallen leaves, improve airflow, and water at soil level." }),
  disease("rust", "Rust", { areas:["leaves", "stems"], symptoms:["orange or rust-colored spots", "yellowing", "browning"], conditions:["heavy rain", "high humidity"], inspect:"Inspect leaf undersides for orange, yellow, or brown powdery pustules.", cultural:"Remove affected leaves, reduce leaf wetness, and improve airflow." }),
  disease("early-blight", "Early blight", { areas:["leaves", "stems", "fruit"], symptoms:["black spots", "yellowing", "browning", "fruit spots"], plantTerms:["tomato", "potato", "eggplant"], conditions:["heat", "heavy rain", "high humidity"], inspect:"Look for concentric rings in older leaf lesions and dark stem or fruit spots.", cultural:"Remove affected lower leaves, mulch against soil splash, and avoid overhead watering." }),
  disease("late-blight", "Late blight", { areas:["leaves", "stems", "fruit", "whole plant"], symptoms:["browning", "black spots", "wilting", "sudden collapse", "rot"], plantTerms:["tomato", "potato"], conditions:["cloudy", "heavy rain", "high humidity"], inspect:"Look for rapidly enlarging water-darkened lesions and pale growth beneath leaves.", cultural:"Isolate the plant, avoid handling wet foliage, and seek prompt extension-office confirmation if spreading." }),
  disease("bacterial-leaf-spot", "Bacterial leaf spot", { areas:["leaves", "fruit"], symptoms:["black spots", "yellowing", "spots", "holes"], conditions:["heavy rain", "high humidity"], inspect:"Inspect for angular or water-darkened spots that may tear into small holes.", cultural:"Avoid working wet plants, sanitize tools, and reduce splash between plants." }),
  disease("fungal-leaf-spot", "Fungal leaf spot", { areas:["leaves"], symptoms:["black spots", "brown spots", "yellowing", "browning", "spots"], conditions:["heavy rain", "high humidity", "cloudy"], inspect:"Compare spot shape on upper and lower leaf surfaces and note whether lesions are spreading upward.", cultural:"Remove affected debris, improve airflow, and keep irrigation off foliage." }),
  disease("anthracnose", "Anthracnose", { areas:["leaves", "stems", "fruit"], symptoms:["black spots", "cankers", "rot", "fruit spots", "dieback"], conditions:["heavy rain", "high humidity"], inspect:"Look for sunken dark lesions on fruit or stems and small dark fruiting bodies.", cultural:"Prune affected tissue in dry weather, clean tools, and remove fallen debris." }),
  disease("fire-blight", "Fire blight", { areas:["stems", "flowers", "fruit", "bark"], symptoms:["dieback", "browning", "discoloration", "sap or gum", "blossom drop"], plantTerms:["apple", "pear", "quince"], conditions:["heat", "heavy rain"], inspect:"Check for blackened shoot tips curved like a shepherd’s crook and bacterial ooze.", cultural:"Avoid nitrogen stimulation, disinfect tools between cuts, and seek extension guidance before major pruning." }),
  disease("root-rot", "Root rot", { areas:["roots", "whole plant"], symptoms:["wilting", "stunted growth", "sudden collapse", "poor vigor", "root rot smell", "loose plant"], conditions:["heavy rain", "recent watering"], inspect:"Check soil moisture, drainage, root firmness, and whether roots are pale and firm or dark and soft.", cultural:"Pause unnecessary watering, improve drainage, and protect viable roots from further saturation." }),
  disease("damping-off", "Damping off", { areas:["stems", "roots", "whole plant"], symptoms:["soft rot", "sudden collapse", "stunted growth"], conditions:["recent planting", "recent watering", "high humidity"], inspect:"Inspect the stem at soil level for thinning, darkening, or soft collapse in seedlings.", cultural:"Improve airflow, reduce surface moisture, and use clean containers and media for future sowing." }),
  disease("canker", "Canker", { areas:["stems", "bark"], symptoms:["cankers", "cracking", "discoloration", "sap or gum", "dieback"], inspect:"Inspect the boundary between healthy bark and sunken or cracked tissue.", cultural:"Protect bark from injury, sanitize tools, and prune only after confirming suitable timing for the plant." }),
  disease("botrytis", "Botrytis / gray mold", { areas:["leaves", "flowers", "fruit", "stems"], symptoms:["rot", "browning", "blossom drop", "spots", "soft rot"], conditions:["cloudy", "heavy rain", "high humidity"], inspect:"Look for fuzzy gray growth on fading flowers, fruit, or soft damaged tissue.", cultural:"Remove infected material, improve airflow, and reduce prolonged surface moisture." }),
  disease("sooty-mold", "Sooty mold", { areas:["leaves", "stems", "fruit"], symptoms:["black spots", "sticky residue"], pests:["aphids", "whiteflies", "scale", "mealybugs"], inspect:"Check whether the dark coating wipes away and inspect above it for honeydew-producing insects.", cultural:"Address the sap-feeding pest source and rinse residue gently when plant-safe." }),

  pest("aphids", "Aphids", { areas:["leaves", "stems", "flowers"], symptoms:["curling", "sticky residue", "distorted growth", "yellowing"], pests:["aphids", "ants"], inspect:"Inspect tender tips and leaf undersides for clustered pear-shaped insects and shed skins.", cultural:"Use a firm water spray where suitable, prune badly infested tips, and protect beneficial insects." }),
  pest("spider-mites", "Spider mites", { areas:["leaves", "whole plant"], symptoms:["mottling", "webbing", "yellowing", "scorched edges", "poor vigor"], pests:["mites", "webs"], conditions:["heat", "drought"], inspect:"Tap foliage over white paper and check leaf undersides for fine webbing and moving specks.", cultural:"Reduce plant water stress, rinse leaf undersides when appropriate, and isolate severe infestations." }),
  pest("whiteflies", "Whiteflies", { areas:["leaves", "whole plant"], symptoms:["yellowing", "sticky residue", "poor vigor"], pests:["whiteflies"], inspect:"Gently disturb foliage and watch for tiny white insects flying from leaf undersides.", cultural:"Remove badly infested leaves, use monitoring cards, and conserve predatory insects." }),
  pest("scale", "Scale insects", { areas:["leaves", "stems", "bark"], symptoms:["sticky residue", "yellowing", "poor vigor", "dieback"], pests:["scale", "ants"], inspect:"Look for immobile shell-like bumps along stems, veins, and leaf undersides.", cultural:"Confirm live scale before treatment, remove small colonies mechanically, and prune severe pockets." }),
  pest("mealybugs", "Mealybugs", { areas:["leaves", "stems", "roots"], symptoms:["sticky residue", "yellowing", "poor vigor", "distorted growth"], pests:["mealybugs", "ants"], inspect:"Inspect leaf joints and protected crevices for white cottony clusters.", cultural:"Isolate affected container plants and remove visible colonies with plant-safe mechanical methods." }),
  pest("japanese-beetles", "Japanese beetles", { areas:["leaves", "flowers", "fruit"], symptoms:["holes", "skeletonized leaves", "poor fruit set"], pests:["beetles"], inspect:"Look for metallic beetles feeding together and lace-like skeletonized foliage.", cultural:"Hand-pick into soapy water in the cool morning and protect blooms without trapping more beetles nearby." }),
  pest("flea-beetles", "Flea beetles", { areas:["leaves"], symptoms:["holes", "stunted growth"], pests:["beetles"], plantTerms:["eggplant", "tomato", "pepper", "brassica"], inspect:"Look for many tiny round shot holes and small jumping beetles.", cultural:"Protect young plants with exclusion fabric where pollination is not needed and reduce weed hosts." }),
  pest("squash-vine-borer", "Squash vine borer", { areas:["stems", "whole plant"], symptoms:["wilting", "boring holes", "sudden collapse", "dieback"], pests:["frass", "worms or larvae"], plantTerms:["squash", "zucchini", "pumpkin"], inspect:"Inspect the lower stem for entry holes, sawdust-like frass, and internal larvae.", cultural:"Confirm the entry site before carefully removing larvae; protect future stems during egg-laying season." }),
  pest("tomato-hornworm", "Tomato hornworm", { areas:["leaves", "fruit", "stems"], symptoms:["holes", "skeletonized leaves", "fruit spots"], pests:["caterpillars", "frass", "worms or larvae"], plantTerms:["tomato", "pepper"], inspect:"Search beneath damaged foliage for large green caterpillars and dark droppings.", cultural:"Hand-pick when practical and preserve parasitized hornworms carrying white beneficial-wasp cocoons." }),
  pest("caterpillar-damage", "Caterpillar damage", { areas:["leaves", "flowers", "fruit"], symptoms:["holes", "skeletonized leaves", "worms or larvae"], pests:["caterpillars", "frass", "eggs", "worms or larvae"], inspect:"Inspect leaf undersides, rolled leaves, and nearby stems for larvae, eggs, or frass.", cultural:"Hand-pick or exclude where feasible and identify the caterpillar before selecting controls." }),
  pest("slugs-snails", "Slugs and snails", { areas:["leaves", "stems", "fruit"], symptoms:["holes", "poor vigor"], pests:["slugs or snails"], conditions:["heavy rain"], inspect:"Check at dusk or dawn for slime trails and irregular holes near soil level.", cultural:"Remove hiding places, hand-pick, and adjust irrigation timing to reduce overnight surface moisture." }),
  pest("leaf-miners", "Leaf miners", { areas:["leaves"], symptoms:["mottling", "distorted growth", "yellowing"], pests:["worms or larvae"], inspect:"Hold leaves to light and look for winding pale tunnels containing larvae or dark frass.", cultural:"Remove a limited number of badly mined leaves and protect new growth when practical." }),
  pest("thrips", "Thrips", { areas:["leaves", "flowers", "fruit"], symptoms:["mottling", "distorted growth", "poor fruit set", "blossom drop", "spots"], pests:["unsure"], conditions:["heat"], inspect:"Tap flowers over white paper and look for slender moving insects and silvery feeding scars.", cultural:"Remove spent blooms, reduce weed hosts, and use monitoring cards to confirm activity." }),

  stress("overwatering", "Overwatering", { areas:["roots", "leaves", "whole plant"], symptoms:["yellowing", "wilting", "poor vigor", "root rot smell", "loose plant"], conditions:["recent watering", "heavy rain"], inspect:"Check moisture below the surface, drainage, and whether symptoms persist while soil remains wet.", cultural:"Let soil reach the plant’s appropriate moisture level and correct drainage or irrigation frequency." }),
  stress("underwatering", "Underwatering", { areas:["leaves", "whole plant"], symptoms:["wilting", "browning", "scorched edges", "fruit drop", "poor vigor"], conditions:["drought", "heat"], inspect:"Check moisture at root depth and compare morning versus afternoon wilt.", cultural:"Rehydrate gradually at the root zone and use mulch where suitable without burying the crown." }),
  stress("heat-stress", "Heat stress", { areas:["leaves", "flowers", "fruit", "whole plant"], symptoms:["wilting", "scorched edges", "blossom drop", "fruit drop", "poor fruit set"], conditions:["heat", "drought"], inspect:"Compare damage on the hottest exposure and note whether plants recover overnight.", cultural:"Provide appropriate temporary shade, maintain even root-zone moisture, and avoid heat-period pruning or feeding." }),
  stress("sun-scorch", "Sun scorch", { areas:["leaves", "fruit", "bark"], symptoms:["scorched edges", "browning", "spots", "cracking"], conditions:["heat"], inspect:"Look for damage concentrated on the sun-facing side after a sudden exposure change.", cultural:"Prevent abrupt exposure changes and protect vulnerable bark or fruit with plant-appropriate shade." }),
  stress("frost-injury", "Frost injury", { areas:["leaves", "flowers", "fruit", "stems", "whole plant"], symptoms:["black spots", "browning", "wilting", "blossom drop", "fruit drop", "sudden collapse"], conditions:["frost"], inspect:"Check whether exposed tender tissue is darkened or water-soaked after a cold event.", cultural:"Wait for the full extent of injury to become clear before pruning and protect tender growth from another frost." }),
  stress("wind-damage", "Wind damage", { areas:["leaves", "stems", "fruit", "whole plant"], symptoms:["torn leaves", "browning", "scorched edges", "fruit drop", "one-sided dieback"], conditions:["wind"], inspect:"Look for injury concentrated on the windward side, broken petioles, and rubbed stems.", cultural:"Stake only when needed, reduce rubbing, and provide a breathable windbreak without trapping humidity." }),
  stress("transplant-shock", "Transplant shock", { areas:["roots", "leaves", "whole plant"], symptoms:["wilting", "yellowing", "stunted growth", "poor vigor", "leaf drop"], conditions:["repotting or transplanting", "recent planting"], inspect:"Confirm timing relative to planting and inspect moisture around—not only inside—the original root ball.", cultural:"Minimize further disturbance, maintain appropriate moisture, and delay fertilizer until active recovery." }),
  stress("nutrient-deficiency", "Nutrient deficiency", { areas:["leaves", "whole plant"], symptoms:["yellowing", "mottling", "poor vigor", "stunted growth", "distorted growth"], inspect:"Note whether symptoms begin on old or new leaves and consider a soil or tissue test before supplementing.", cultural:"Check pH, drainage, and root health before applying a targeted nutrient supported by testing." }),
  stress("fertilizer-burn", "Fertilizer burn", { areas:["leaves", "roots", "whole plant"], symptoms:["scorched edges", "browning", "wilting", "poor vigor"], conditions:["recent feeding"], inspect:"Confirm timing after feeding and look for salt crust, root injury, or uniform marginal scorch.", cultural:"Stop additional feeding and follow product-label guidance for safe leaching where drainage permits." }),
  stress("poor-pollination", "Poor pollination", { areas:["flowers", "fruit"], symptoms:["blossom drop", "poor fruit set", "malformed fruit", "fruit drop"], conditions:["heat", "wind", "heavy rain"], inspect:"Observe flower timing, pollinator activity, temperature, and whether compatible pollen sources are present.", cultural:"Protect pollinators, avoid spraying during bloom, and support appropriate compatible flowering plants." }),
  stress("soil-compaction", "Soil compaction", { areas:["roots", "whole plant"], symptoms:["stunted growth", "poor vigor", "uneven growth", "wilting"], inspect:"Compare soil resistance and drainage inside and outside the affected root zone without severing major roots.", cultural:"Avoid traffic, improve surface organic matter, and use plant-appropriate aeration methods cautiously." }),
  stress("seasonal-dormancy", "Normal seasonal dormancy", { areas:["leaves", "whole plant"], symptoms:["yellowing", "leaf drop", "poor vigor", "dieback"], conditions:["frost"], inspect:"Compare timing with the species’ normal seasonal cycle and inspect buds or stems for living tissue.", cultural:"Continue species-appropriate dormant care and avoid forcing growth before the normal season." }),
];

export const supportedPlantHealthConditions = plantHealthRules.map(({ name }) => name);
export const plantHealthCategories = ["Disease", "Pest", "Environmental stress"];

