import React, { useMemo, useState } from "react";
import { useGarden } from "../../context/GardenContext";
import { useEstateEnvironment } from "../../context/EstateEnvironmentContext";
import { companions } from "../../services/conservatoryService";
import ConservatoryChat from "./ConservatoryChat";
import "./Conservatory.css";

const defaults={enabled:true,externalAI:false,includeJournal:true,includeTea:true,includeWeather:true,storeHistory:true,defaultCompanion:"buddy"};
const loadSettings=()=>{try{return{...defaults,...JSON.parse(localStorage.getItem("jardinSoleilConservatorySettings")||"{}")};}catch{return defaults;}};
export default function Conservatory({onNavigate,initialCompanion,scopePlant,initialSettingsOpen=false}){
  const garden=useGarden();const environment=useEstateEnvironment();const [settings,setSettings]=useState(loadSettings);const [selected,setSelected]=useState(initialCompanion||settings.defaultCompanion);const [showSettings,setShowSettings]=useState(initialSettingsOpen);
  const update=(key,value)=>{const next={...settings,[key]:value};setSettings(next);localStorage.setItem("jardinSoleilConservatorySettings",JSON.stringify(next));};
  const data=useMemo(()=>({plants:garden.activePlants,journalEntries:settings.includeJournal?garden.journalEntries:[],photos:garden.photos,plantDiagnoses:garden.plantDiagnoses,plantIdentifications:garden.plantIdentifications,teaWorkflows:settings.includeTea?garden.teaWorkflows:[],teaBlends:settings.includeTea?garden.teaRecipes:[],inventoryItems:garden.inventoryItems,stats:garden.stats,environment:settings.includeWeather?environment:{status:"disabled"}}),[garden.activePlants,garden.journalEntries,garden.photos,garden.plantDiagnoses,garden.plantIdentifications,garden.teaWorkflows,garden.teaRecipes,garden.inventoryItems,garden.stats,environment,settings.includeJournal,settings.includeTea,settings.includeWeather]);
  if(!settings.enabled)return <section className="js-conservatory"><header><p>Jardin Soleil</p><h1>The Conservatory</h1></header><div className="js-conservatory__empty"><h2>The Conservatory is turned off.</h2><button type="button" onClick={()=>update("enabled",true)}>Turn on The Conservatory</button></div></section>;
  return <section className="js-conservatory js-estate-page" aria-labelledby="conservatory-title"><header className="js-conservatory__hero"><div><p>Jardin Soleil · Intelligent Garden Companions</p><h1 id="conservatory-title">The Conservatory</h1><span>{scopePlant?`Consulting about ${scopePlant.name}`:"Three perspectives, one truthful estate record."}</span></div><div className="js-conservatory__hero-actions">{selected==="gardener"&&<button type="button" onClick={()=>onNavigate("Plant Finder")}>Plant Finder</button>}<button type="button" onClick={()=>onNavigate("Plant Health Center")}>Plant Health Center</button><button type="button" onClick={()=>setShowSettings((v)=>!v)}>Conservatory Settings</button></div></header>
    {showSettings&&<ConservatorySettings settings={settings} update={update}/>}<div className="js-conservatory__companions">{Object.entries(companions).map(([id,item])=><button type="button" key={id} className={selected===id?"is-selected":""} aria-pressed={selected===id} onClick={()=>setSelected(id)}><span aria-hidden="true">{id==="buddy"?"B":id==="gardener"?"G":"H"}</span><strong>{item.name}</strong><small>{item.title}</small><p>{item.tone}</p></button>)}</div>
    <ConservatoryChat key={`${selected}-${scopePlant?.id||"estate"}`} companion={selected} data={data} scopePlant={scopePlant} settings={settings} onNavigate={(action)=>{if(action.plantId){const plant=garden.activePlants.find((p)=>p.id===action.plantId);if(plant)garden.setSelectedPlant(plant);}onNavigate(action.page);}}/>
    <p className="js-conservatory__privacy">Privacy: answers use selected saved garden records in this browser. External mode, when enabled and securely configured, sends only the current question, scoped plant, source labels, and local answer—not local storage, notes wholesale, API keys, or photo files.</p>
  </section>;
}
function ConservatorySettings({settings,update}){return <aside className="js-conservatory__settings" aria-label="Conservatory settings">{[["enabled","The Conservatory"],["externalAI","External AI"],["includeJournal","Include journal entries"],["includeTea","Include Tea Apothecary data"],["includeWeather","Include weather context"],["storeHistory","Store conversation history"]].map(([key,label])=><label key={key}><span>{label}</span><input type="checkbox" checked={settings[key]} onChange={(e)=>update(key,e.target.checked)}/></label>)}<label><span>Default companion</span><select value={settings.defaultCompanion} onChange={(e)=>update("defaultCompanion",e.target.value)}><option value="buddy">Buddy</option><option value="gardener">Head Gardener</option><option value="herbalist">Herbalist</option></select></label><button type="button" onClick={()=>{localStorage.removeItem("jardinSoleilConservatoryHistory");window.dispatchEvent(new Event("conservatory-history-cleared"));}}>Clear conversation history</button></aside>}
