import React, { useEffect, useRef, useState } from "react";
import { answerWithOptionalExternal, companions } from "../../services/conservatoryService";
const reports=["Daily Estate Update","Weekly Garden Report","Monthly Garden Summary","Orchard Health Report","Harvest Report","Tea Apothecary Inventory Report","Seasonal Care Review"];
const loadHistory=(enabled)=>{if(!enabled)return[];try{return JSON.parse(localStorage.getItem("jardinSoleilConservatoryHistory")||"[]");}catch{return[];}};
export default function ConservatoryChat({companion,data,scopePlant,settings,onNavigate}){const [messages,setMessages]=useState(()=>loadHistory(settings.storeHistory).filter((m)=>m.companion===companion&&m.scopePlantId===(scopePlant?.id||null)));const [text,setText]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const inputRef=useRef(null);const info=companions[companion];
  useEffect(()=>{const clear=()=>setMessages([]);window.addEventListener("conservatory-history-cleared",clear);return()=>window.removeEventListener("conservatory-history-cleared",clear);},[]);
  const persist=(next)=>{if(!settings.storeHistory)return;let all=loadHistory(true).filter((m)=>!(m.companion===companion&&m.scopePlantId===(scopePlant?.id||null)));localStorage.setItem("jardinSoleilConservatoryHistory",JSON.stringify([...all,...next].slice(-100)));};
  const send=async(value=text)=>{const question=value.trim();if(!question||loading)return;const user={id:`u-${Date.now()}`,role:"user",text:question,companion,scopePlantId:scopePlant?.id||null,timestamp:new Date().toISOString(),sources:[]};const pending=[...messages,user];setMessages(pending);setText("");setLoading(true);setError("");try{const answer=await answerWithOptionalExternal({question,companion,data,scopePlant,settings});const next=[...pending,{id:`a-${Date.now()}`,role:"assistant",companion,scopePlantId:scopePlant?.id||null,...answer}];setMessages(next);persist(next);}catch{setError("The Conservatory could not prepare an answer. Your saved garden data was not changed.");}finally{setLoading(false);requestAnimationFrame(()=>inputRef.current?.focus());}};
  return <div className="js-conservatory__chat"><div className="js-conservatory__chat-head"><div><p>Consulting</p><h2>{info.name}{scopePlant?` · ${scopePlant.name}`:""}</h2></div><button type="button" onClick={()=>{setMessages([]);persist([]);}}>Clear conversation</button></div>
    <div className="js-conservatory__suggestions" aria-label="Suggested questions">{(scopePlant?["When was this plant last watered?","What care is overdue?","Summarize this plant’s history.","What should I watch for this season?"]:info.prompts).map((prompt)=><button type="button" key={prompt} onClick={()=>send(prompt)}>{prompt}</button>)}</div>
    <div className="js-conservatory__reports"><strong>Estate reports</strong>{reports.map((report)=><button type="button" key={report} onClick={()=>send(report)}>{report}</button>)}</div>
    <div className="js-conservatory__messages" role="log" aria-live="polite" aria-label={`${info.name} conversation`}>{messages.length?messages.map((message)=><article key={message.id} className={`is-${message.role}`}><header><strong>{message.role==="user"?"You":info.name}</strong><time dateTime={message.timestamp}>{new Date(message.timestamp).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</time></header><p>{message.text}</p>{message.mode&&<small>{message.mode}</small>}{message.sources?.length>0&&<details><summary>Sources from saved records ({message.sources.length})</summary><ul>{message.sources.map((item,index)=><li key={`${item.type}-${item.id}-${index}`}>{item.type}: {item.label}</li>)}</ul></details>}{message.actions?.length>0&&<div>{message.actions.map((action)=><button type="button" key={`${action.page}-${action.label}`} onClick={()=>onNavigate(action)}>{action.label}</button>)}</div>}</article>):<p className="js-conservatory__empty">Choose a suggestion or ask about a saved Jardin Soleil record.</p>}{loading&&<p role="status">{info.name} is reviewing relevant estate records…</p>}</div>
    {error&&<p role="alert" className="js-conservatory__error">{error}</p>}{companion==="herbalist"&&<p className="js-conservatory__wellness">Wellness information describes traditional or commonly associated uses and is not medical advice.</p>}
    <form onSubmit={(e)=>{e.preventDefault();send();}}><label htmlFor="conservatory-message">Message {info.name}</label><div><textarea id="conservatory-message" ref={inputRef} rows="3" value={text} onChange={(e)=>setText(e.target.value)} placeholder="Ask about your saved garden records…"/><button type="submit" disabled={loading||!text.trim()}>Send</button></div></form>
  </div>}
